"""Create table Escola

Revision ID: 5692068a6cfa
Revises: d4e091ed6546
Create Date: 2024-08-01 21:00:01.463035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5692068a6cfa'
down_revision = 'd4e091ed6546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('data_fundacao', sa.DateTime(), nullable=False),
    sa.Column('telefone', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escola')
    # ### end Alembic commands ###
